<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Author</name>
   <tag></tag>
   <elementGuidId>ccd8f521-3b53-4662-bea1-f29f2b9b4321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='author-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#author-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e0dccdc7-7d28-4254-b8ba-205ba1f12eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>88013d7b-b8f6-4f4d-814f-4590b26c284e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>author-label</value>
      <webElementGuid>5cd295f5-a575-4630-bcdf-75d8efb6a20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Author : </value>
      <webElementGuid>b469630d-16a5-4db2-8bcb-4554020652a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;author-label&quot;)</value>
      <webElementGuid>0baf4703-47bb-4f47-b038-1dcb3d8fb65f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='author-label']</value>
      <webElementGuid>42ad5fd5-953b-4222-8535-966351adddf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='author-wrapper']/div/label</value>
      <webElementGuid>3c4f066d-6e90-48be-8867-d1b51008291e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A Working Introduction'])[1]/following::label[1]</value>
      <webElementGuid>82efd762-c826-48d0-b086-16a261bdb3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Title :'])[1]/following::label[2]</value>
      <webElementGuid>047ec6d9-1b57-41b0-a5bf-dc04373efeb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Richard E. Silverman'])[1]/preceding::label[1]</value>
      <webElementGuid>18959450-467b-4ebf-a0f4-27babeade491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publisher :'])[1]/preceding::label[2]</value>
      <webElementGuid>08baaac2-782d-42fb-94a7-a28a4e286801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Author :']/parent::*</value>
      <webElementGuid>afd0706e-d252-4aa5-a69b-ae9f497786be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>d2ce318f-58c0-4094-8590-7f80e02f39b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'author-label' and (text() = 'Author : ' or . = 'Author : ')]</value>
      <webElementGuid>5940ee51-abf6-4192-9dd2-f6deb8b94de8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
