<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Title</name>
   <tag></tag>
   <elementGuidId>374578d7-29b7-4d4a-91a7-6c1b768bba62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='title-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#title-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a794deff-17d3-4dca-9f02-827b96eae129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>4049c521-4086-4fa0-8d79-eeb29b57015b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title-label</value>
      <webElementGuid>20f59b78-5242-40b2-a09a-61d8ef2d5be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Title : </value>
      <webElementGuid>38ff71e9-d8e9-4612-b3d9-ceaab656f2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-label&quot;)</value>
      <webElementGuid>2359684b-2503-48db-b7fa-d5ca8f9df6ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='title-label']</value>
      <webElementGuid>262e5641-ac79-4f2f-b809-04f1e220ebca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title-wrapper']/div/label</value>
      <webElementGuid>3be78013-041a-46cd-835c-097281500b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISBN :'])[1]/following::label[2]</value>
      <webElementGuid>bb4869ab-50bb-4ea4-b123-91bb2f80226b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::label[3]</value>
      <webElementGuid>b0e5cdb1-41ee-48a3-b32b-a3e86e47f804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Git Pocket Guide'])[1]/preceding::label[1]</value>
      <webElementGuid>c998f8cf-bb8a-4a70-9845-45f8692e3d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub Title :'])[1]/preceding::label[2]</value>
      <webElementGuid>aa3ada37-3e70-4491-89bf-8679854ce150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Title :']/parent::*</value>
      <webElementGuid>d826ec92-6232-4006-8f43-28623e736fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>38cc257b-6283-4245-8704-a77ebb8ff430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'title-label' and (text() = 'Title : ' or . = 'Title : ')]</value>
      <webElementGuid>ea164b32-3c8f-4cad-8a06-fe871d88b3c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
