<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RedBlueGreenYellowPurpleBlackWhiteVo_537a50</name>
   <tag></tag>
   <elementGuidId>b06e2c38-c542-4751-bd79-1d2b0be48c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='oldSelectMenu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oldSelectMenu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c8eb3137-1898-4fa2-90de-187308897866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldSelectMenu</value>
      <webElementGuid>ee9f0fc2-400f-46e7-a322-89d66df0ef05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua</value>
      <webElementGuid>83b6450d-e57b-4ef8-b117-03e0623b2111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldSelectMenu&quot;)</value>
      <webElementGuid>ca7f0aff-0803-4569-a114-adb8dc308e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87cd6e01-18fe-4dfd-a137-d82c38976773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldSelectMenu</value>
      <webElementGuid>321eb3aa-6afa-4ccf-9b4f-dc15d12f860c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua</value>
      <webElementGuid>2db6ae31-cbb8-4786-8e6b-0a7911a73425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldSelectMenu&quot;)</value>
      <webElementGuid>22734c05-6601-44cf-9fb9-402bd0600d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc03fe06-e4ce-4e79-8dbf-03bbb7ffeca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldSelectMenu</value>
      <webElementGuid>7b2ee8f0-91f0-4ff1-91fe-df49420e5e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua</value>
      <webElementGuid>488004c5-9f09-4da2-bc9b-3c1a59618c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldSelectMenu&quot;)</value>
      <webElementGuid>2382f5ff-8d35-4db9-9887-322c6efb62ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='oldSelectMenu']</value>
      <webElementGuid>39d066fe-1abc-49b5-9989-2fdff73f36e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectMenuContainer']/div[6]/div/div/select</value>
      <webElementGuid>4eb9fe57-1a2f-4cbf-9822-01660d4a75f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Old Style Select Menu'])[1]/following::select[1]</value>
      <webElementGuid>e9b3aa34-a0b3-44a4-b703-c33fe3281418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::select[1]</value>
      <webElementGuid>7fd0f23e-46ce-41ef-aa6f-ec530adf42da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiselect drop down'])[1]/preceding::select[1]</value>
      <webElementGuid>5ff5aa59-8d13-4b27-88ba-7bf289a36995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/preceding::select[1]</value>
      <webElementGuid>d2039f86-ccc0-4f85-b3cf-761a48e34769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e86013ec-8834-4022-bf38-8edd56d0d700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'oldSelectMenu' and (text() = 'RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua' or . = 'RedBlueGreenYellowPurpleBlackWhiteVoiletIndigoMagentaAqua')]</value>
      <webElementGuid>44381879-763c-4310-8e54-abdf23635bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
